### PR TITLE
33 feature calculate average base acres by program instead of total in commodities

### LINKED ISSUE #33: [FEATURE] Calculate average base acres and recipient count by program instead of total in commodities
**Is your feature request related to a problem? Please describe.**
Currently, we are calculating the total of base acres and recipient count from 2018 to 2022. This is incorrect, as the area and the recipient don't cumulatively increase.

**Describe the solution you'd like**
Calculate the average base acres and average recipient count per program and use that in the Title 1 commodities JSON documents.

**Describe alternatives you've considered**

**Additional context**

### LINKED ISSUE #35: [FEATURE] Exclude 2018 data when calculating base acres and recipient counts
**Is your feature request related to a problem? Please describe.**
The research team discovered some issues in the 2018 base acres raw data. It needs to be excluded for now.

**Describe the solution you'd like**
Exclude 2018 data when calculating average base acres and average recipient count. 

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by sandeep-ps**

### CODE REVIEW

**Comment by sandeep-ps** [comment]
Hi, @pengyin-shan, @navarroc, and @ywkim312, I'm creating this draft PR to change the area calculation to average from sum. Please ignore the map.json file, as it's currently not being used. 

I'm thinking of changing the attribute name to include "average." Wendy, Please let me know if this needs to be changed to the previous attribute name.

From looking at Pandas documentation, I think this is how one would calculate an average of a particular column within a grouping. I still need to confirm if the calculation is correct. I believe Jonathan and the team will also provide their versions of the raw data with the average calculation. I will continue on this task on Monday. Once the calculations are confirmed, applying this to the web service should be a straightforward task.

**Comment by pengyin-shan** [comment]
@sandeep-ps : currently the front-end code is using the `areaInAcres` attribute name. If you like to add `average` to it, I can update all attribute names in the front-end accordingly. 

We can maintain the `areaInAcres` name if there are no cases that we will need total base acres in the future, or change it to 'average'. I'm open to both options.

**Comment by sandeep-ps** [comment]
Hi, Wendy, After a little bit of thought, I feel it's better to clarify what the attribute is about. So, maybe `averageAreaInAcres` is the better of the two. Regarding future possibilities, I'm not sure, but when showing individual years (2018, 2019, etc., ) having a yearly total of acres seems like a possibility and it can show how the area changes between years.

**Comment by sandeep-ps** [comment]
Hi, @ywkim312 and @pengyin-shan, This is ready for review. This PR changes base acres and recipients from total numbers to averages.

**Review by pengyin-shan — APPROVED** [review]

**Comment by pengyin-shan** [comment]
@sandeep-ps , to confirm, the "areaInAcres" in https://policydesignlab-dev.ncsa.illinois.edu/pdl/programs/commodities/state-distribution will be changed to 'averageAreaInAcres' and 'recipientCount' will be changed to 'averageRecipientCount' right? Nothing to do with payments, and nothing gonna to change in https://policydesignlab-dev.ncsa.illinois.edu/pdl/allprograms

**Comment by sandeep-ps** [comment]
> @sandeep-ps , to confirm, the "areaInAcres" in https://policydesignlab-dev.ncsa.illinois.edu/pdl/programs/commodities/state-distribution will be changed to 'averageAreaInAcres' and 'recipientCount' will be changed to 'averageRecipientCount' right? Nothing to do with payments, and nothing gonna to change in https://policydesignlab-dev.ncsa.illinois.edu/pdl/allprograms

Yes, that's right about the names. As discussed in Slack, one other change excludes base acres and recipient data for 2018.

**Review by ywkim312 — APPROVED** [review]

**Pull request merged**
