### PR TITLE
Added missing fields to EQIP and CSP json

### LINKED ISSUE #89: Add missing fields in EQIP data
When the data structure change happens, some field got missing like "TotalPaymentInPercentageNationwide" and "totalPaymentInDolloars" for whole statue. Add those to the output data json

### LINKED ISSUE #90: Add missing fields in CSP data
When the data structure change happens, some field got missing like "TotalPaymentInPercentageNationwide" and "totalPaymentInDolloars" for whole statue. Add those to the output data json

### PR DESCRIPTION
**Pull request by ywkim312**

### CODE REVIEW

**Review by pengyin-shan — APPROVED** [review]
Thank you, @ywkim312! This is exactly what I need for EQIP!

Regarding CSP, I have a quick question. I noticed that the totalPaymentInDollars and totalPaymentInPercentageNationwide are already available in the CSP state-distribution endpoint: https://policydesignlab-dev.ncsa.illinois.edu/pdl/titles/title-ii/programs/csp/state-distribution

Given that CSP seems to already have these two data points, will the changes proposed in this PR impact the CSP state-distribution? EQIP definitely requires these data points, but it appears that CSP already includes them.

**Review by sandeep-ps — APPROVED** [review]
I checked briefly. It looks good to me. Please see Pengyin's question.

**Comment by ywkim312** [comment]
> Thank you, @ywkim312! This is exactly what I need for EQIP!
> 
> Regarding CSP, I have a quick question. I noticed that the totalPaymentInDollars and totalPaymentInPercentageNationwide are already available in the CSP state-distribution endpoint: https://policydesignlab-dev.ncsa.illinois.edu/pdl/titles/title-ii/programs/csp/state-distribution
> 
> Given that CSP seems to already have these two data points, will the changes proposed in this PR impact the CSP state-distribution? EQIP definitely requires these data points, but it appears that CSP already includes them.

I don't see those in csp? Can you check again?

**Comment by ywkim312** [comment]
> Thank you, @ywkim312! This is exactly what I need for EQIP!
> 
> Regarding CSP, I have a quick question. I noticed that the totalPaymentInDollars and totalPaymentInPercentageNationwide are already available in the CSP state-distribution endpoint: https://policydesignlab-dev.ncsa.illinois.edu/pdl/titles/title-ii/programs/csp/state-distribution
> 
> Given that CSP seems to already have these two data points, will the changes proposed in this PR impact the CSP state-distribution? EQIP definitely requires these data points, but it appears that CSP already includes them.

Oh I see what you mean. Let me check one more time

**Comment by pengyin-shan** [comment]
Ohhh never mind @ywkim312! I was checking https://policydesignlab-dev.ncsa.illinois.edu/pdl/titles/title-ii/programs/csp/state-distribution and misinterpret the ones inside statutes, where your added ones are out of statutes:
Screenshot 2024-02-14 at 10 37 28 AM

**Comment by ywkim312** [comment]
Yes the thing in CSP is only statute total not the state totla

**Comment by pengyin-shan** [comment]
@ywkim312  please go ahead with both EQIP and CSP 👍. They both need totalPaymentInDollars and totalPaymentInPercentageNationwide for the whole state

**Pull request merged**
