### PR TITLE
Updated DMC / SADA to match with ARC PLC

### LINKED ISSUE #61: Update DMC / SADA to match with ARC PLC
Update DMC / SADA parser to fit with ARC PLC data format 

1. Make state name as abbreviation
2. Rename paymentInDollars to programPaymentInDollars
3. Rename count to averageRecipientCount
4. Rename programName in subProgram to subProgramName
5. Use full name for categories instead of abbreviation

### PR DESCRIPTION
**Pull request by ywkim312**

### CODE REVIEW

**Comment by sandeep-ps** [comment]
Please update the CHANGELOG. The rest looks good to me. Thanks.

**Comment by ywkim312** [comment]
> Please update the CHANGELOG. The rest looks good to me. Thanks.

the change log entry is already in there? 
- Dairy and Disaster data import program and generate JSON files. [#59](https://github.com/policy-design-lab/data-import/issues/59)

It was just adding some information of the json only. If I need to create an issue and need to add changelog, then I will do

**Comment by ywkim312** [comment]
> Please update the CHANGELOG. The rest looks good to me. Thanks.

The reason why was because it was not released yet so just modified the json only to get the final approval

**Comment by sandeep-ps** [comment]
Hi, @ywkim312, on this PR, I do not see a CHANGELOG update. 

image

You have linked #61 to this PR, right? Shouldn't that be added to the CHANGELOG?

**Comment by ywkim312** [comment]
> Hi, @ywkim312, on this PR, I do not see a CHANGELOG update.
> 
> image
> 
> You have linked #61 to this PR, right? Shouldn't that be added to the CHANGELOG?

Oh sorry, my explanation was bad. This PR doesn't have changelog it is because it was just update of json that was the part of not released issue in API part. So I wanted this to be the part of the DMC/SADA release instead of the separated issue. But since you insist, I will add it.

**Comment by ywkim312** [comment]
changelog updated

**Review by pengyin-shan — APPROVED** [review]

**Comment by sandeep-ps** [comment]
> changelog updated

Sorry, I don't think I fully understand what you explained. Thanks for updating the CHANGELOG of this repo as it's good for future reference. On a side note, we haven't started releasing this repo yet, but it's something that we need to consider in the near future. Thanks.

**Review by sandeep-ps — APPROVED** [review]

**Comment by ywkim312** [comment]
> > changelog updated
> 
> Sorry, I don't think I fully understand what you explained. Thanks for updating the CHANGELOG of this repo as it's good for future reference. On a side note, we haven't started releasing this repo yet, but it's something that we need to consider in the near future. Thanks.



> > changelog updated
> 
> Sorry, I don't think I fully understand what you explained. Thanks for updating the CHANGELOG of this repo as it's good for future reference. On a side note, we haven't started releasing this repo yet, but it's something that we need to consider in the near future. Thanks.

Hmm sorry about my bad explanation. The release what I meant was the release of API. I thought I explained it above but maybe not? I have no idea of release this "data-import" repo. :)

**Pull request merged**
