### PR TITLE
Updated summary data to include future prediction data

### LINKED ISSUE #111: Create a EQIP IRA summary data including the future prediction
Create a summary data json for EQIP IRA. The summary should also contain that future predicted data as well

### LINKED ISSUE #112: Update EQIP IRA future prediction data
There was an update of EQIP IRA future prediction data table. The data should be updated using this new data

### PR DESCRIPTION
**Pull request by ywkim312**
The summary data now includes the future prediction data.

### CODE REVIEW

**Review by pengyin-shan — COMMENTED** [review]
Hi @ywkim312, is it possible to have a summary for "2024-2031" instead of year-by-year, since this is how https://policydesignlab-dev.ncsa.illinois.edu/pdl/titles/title-ii/programs/eqip-ira/predicted is organized? And can we also use predictedTotalPaymentInDollars for the predicted part?

**Comment by ywkim312** [comment]
> Hi @ywkim312, is it possible to have a summary for "2024-2031" instead of year-by-year, since this is how https://policydesignlab-dev.ncsa.illinois.edu/pdl/titles/title-ii/programs/eqip-ira/predicted is organized? And can we also use predictedTotalPaymentInDollars for the predicted part?

Updated

**Comment by pengyin-shan** [comment]
Thank you for the update @ywkim312 ! can we also change the `totalPaymentInDollars` to `predictedTotalPaymentInDollars` for 2024-2031 since this attribute is used in the predicted endpoint?

**Comment by ywkim312** [comment]
> Thank you for the update @ywkim312 ! can we also change the `totalPaymentInDollars` to `predictedTotalPaymentInDollars` for 2024-2031 since this attribute is used in the predicted endpoint?

updated

**Review by pengyin-shan — APPROVED** [review]
Looks good, thank you for all the changes @ywkim312 !

**Review by sandeep-ps — APPROVED** [review]
This PR looks good to me too. Approving.

**Pull request merged**
